#!/bin/bash
# Display all weather art styles

echo "=== CLImate Weather Art Gallery ==="
echo ""
echo "Weather codes available:"
echo "  0 = Clear sky"
echo "  1-2 = Partly cloudy"
echo "  3 = Overcast"
echo "  45-48 = Fog"
echo "  51-57 = Drizzle/Freezing drizzle"
echo "  61-67 = Rain/Freezing rain"
echo "  71-77 = Snow"
echo "  80-82 = Rain showers"
echo "  85-86 = Snow showers"
echo "  95 = Thunderstorm"
echo "  96-99 = Thunderstorm with hail"
echo ""
echo "All art is standardized to 9 lines with colors:"
echo "  ☀️  Sun: Yellow"
echo "  ☁️  Clouds: Gray (storm clouds: Dark Gray)"
echo "  💧 Rain: Blue (/)"
echo "  ❄️  Snow: White (*)"
echo "  ⚡ Lightning: Yellow (/_/)"
echo ""
